### PR TITLE
Fixing summary

### PR DESCRIPTION
**Pull request by szepeviktor**
Please consider taking a look at the Debian package's details
https://github.com/wp-cli/wp-cli/blob/master/utils/wp-cli-updatedeb.sh#L28-L38

### CODE REVIEW

**Comment by SosyalAlkolik** [comment]
I don't understand what I do for resolving the conflict.

**Comment by szepeviktor** [comment]
You can make the changes by hand.

**Comment by SosyalAlkolik** [comment]
Now, is the spec file correct?

**Comment by szepeviktor** [comment]
Yes. Thank you.

**Comment by szepeviktor** [comment]
Maybe you could capitalize `wp-cli` in the description

**Pull request closed without merging**
